# Generated by Django 4.2.7 on 2023-11-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientId', models.AutoField(primary_key=True, serialize=False)),
                ('ClientName', models.CharField(max_length=500)),
                ('ClientNIF', models.IntegerField()),
                ('ClientPhone', models.IntegerField()),
                ('ClientEmail', models.CharField(max_length=500)),
                ('ClientAddress', models.CharField(max_length=500)),
                ('ClientPostCode', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('ContractId', models.AutoField(primary_key=True, serialize=False)),
                ('ContractStart', models.DateField()),
                ('ContractEnd', models.DateField()),
                ('ContractPrice', models.CharField(max_length=500)),
                ('ContractDescription', models.CharField(max_length=500)),
            ],
        ),
    ]
