# Generated by Django 4.2.7 on 2023-11-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_client',
            fields=[
                ('Contract_clientId', models.AutoField(primary_key=True, serialize=False)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.client')),
                ('Contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.contract')),
            ],
        ),
    ]
